package ProjectGUI;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x13332576
 */
public class InfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form InfoFrame
     */
    public InfoFrame() {
        initComponents();
        String URL;
    }


         
       
 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JToggleButton();
        FixtureTbl = new javax.swing.JScrollPane();
        FixTable = new javax.swing.JTable();
        SlideHeader = new javax.swing.JLabel();
        TableHeader = new javax.swing.JLabel();
        Link1 = new javax.swing.JLabel();
        Link2 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        PrevBtn = new javax.swing.JToggleButton();
        NextBtn1 = new javax.swing.JToggleButton();
        StadiumPic = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 710));
        getContentPane().setLayout(null);

        HomeBtn.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn);
        HomeBtn.setBounds(10, 10, 90, 40);

        FixTable.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        FixTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"New Zeland", null, null, null},
                {"England", null, null, null},
                {"France", null, null, null},
                {"Ireland", null, null, null},
                {"Italy", null, null, null},
                {"Samoa", null, null, null},
                {"Australia", null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Team", "Wins", "Loss", "Next Match"
            }
        ));
        FixTable.setToolTipText("");
        FixtureTbl.setViewportView(FixTable);

        getContentPane().add(FixtureTbl);
        FixtureTbl.setBounds(10, 430, 382, 155);

        SlideHeader.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        SlideHeader.setText("Stadiums");
        getContentPane().add(SlideHeader);
        SlideHeader.setBounds(180, 70, 60, 20);

        TableHeader.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TableHeader.setText("Fixtures");
        getContentPane().add(TableHeader);
        TableHeader.setBounds(180, 400, 50, 20);

        Link1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/Paddy-Power.gif"))); // NOI18N
        getContentPane().add(Link1);
        Link1.setBounds(10, 620, 170, 40);

        Link2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/Ticketmaster-logo.jpg"))); // NOI18N
        Link2.setMaximumSize(new java.awt.Dimension(208, 148));
        Link2.setMinimumSize(new java.awt.Dimension(208, 148));
        Link2.setPreferredSize(new java.awt.Dimension(208, 148));
        getContentPane().add(Link2);
        Link2.setBounds(210, 620, 190, 40);

        Title.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        Title.setText("Information page");
        getContentPane().add(Title);
        Title.setBounds(130, 20, 180, 30);

        PrevBtn.setBackground(new java.awt.Color(255, 255, 255));
        PrevBtn.setText("<Previous");
        getContentPane().add(PrevBtn);
        PrevBtn.setBounds(70, 360, 100, 30);

        NextBtn1.setBackground(new java.awt.Color(255, 255, 255));
        NextBtn1.setText("Next >");
        getContentPane().add(NextBtn1);
        NextBtn1.setBounds(250, 360, 100, 30);

        StadiumPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/wembley.jpg"))); // NOI18N
        getContentPane().add(StadiumPic);
        StadiumPic.setBounds(50, 100, 310, 250);

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/running bg.jpg"))); // NOI18N
        getContentPane().add(BackgroundLbl);
        BackgroundLbl.setBounds(0, 0, 410, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        ProjectGUI myProjectGUI= new ProjectGUI();
        myProjectGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JTable FixTable;
    private javax.swing.JScrollPane FixtureTbl;
    private javax.swing.JToggleButton HomeBtn;
    private javax.swing.JLabel Link1;
    private javax.swing.JLabel Link2;
    private javax.swing.JToggleButton NextBtn1;
    private javax.swing.JToggleButton PrevBtn;
    private javax.swing.JLabel SlideHeader;
    private javax.swing.JLabel StadiumPic;
    private javax.swing.JLabel TableHeader;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
