/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectGUI;

/**
 *
 * @author x13564737
 */
public class ProjectGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProjectGUI
     */
    public ProjectGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stadiumLbl = new javax.swing.JLabel();
        jerseyLbl = new javax.swing.JLabel();
        triviaLbl = new javax.swing.JLabel();
        InfoBtn = new javax.swing.JButton();
        TriviaBtn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        TitleBackground = new javax.swing.JLabel();
        StatBtn = new javax.swing.JButton();
        backgroundImgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(15, 15, 400, 600));
        setPreferredSize(new java.awt.Dimension(400, 620));
        getContentPane().setLayout(null);

        stadiumLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/stadiumE.jpg"))); // NOI18N
        getContentPane().add(stadiumLbl);
        stadiumLbl.setBounds(290, 460, 60, 60);

        jerseyLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/jerseyE.jpg"))); // NOI18N
        jerseyLbl.setText("jLabel1");
        getContentPane().add(jerseyLbl);
        jerseyLbl.setBounds(290, 330, 60, 60);

        triviaLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/triviaE.jpg"))); // NOI18N
        triviaLbl.setText("jLabel1");
        getContentPane().add(triviaLbl);
        triviaLbl.setBounds(290, 200, 50, 60);

        InfoBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        InfoBtn.setForeground(new java.awt.Color(51, 102, 255));
        InfoBtn.setText("Location + Fixtures");
        InfoBtn.setOpaque(false);
        InfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(InfoBtn);
        InfoBtn.setBounds(20, 460, 270, 60);

        TriviaBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TriviaBtn.setForeground(new java.awt.Color(51, 102, 255));
        TriviaBtn.setText("Trivia Game");
        TriviaBtn.setOpaque(false);
        TriviaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriviaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(TriviaBtn);
        TriviaBtn.setBounds(20, 200, 270, 60);

        Title.setFont(new java.awt.Font("Leelawadee", 1, 26)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Rugby World Cup 2015 App");
        getContentPane().add(Title);
        Title.setBounds(20, 10, 360, 140);

        TitleBackground.setBackground(new java.awt.Color(0, 153, 153));
        TitleBackground.setForeground(new java.awt.Color(255, 255, 255));
        TitleBackground.setOpaque(true);
        getContentPane().add(TitleBackground);
        TitleBackground.setBounds(10, 50, 380, 60);

        StatBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        StatBtn.setForeground(new java.awt.Color(51, 102, 255));
        StatBtn.setText("Team + Player Stats");
        StatBtn.setOpaque(false);
        StatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatBtnMouseClicked(evt);
            }
        });
        StatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(StatBtn);
        StatBtn.setBounds(20, 330, 270, 60);

        backgroundImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/backgroundE.jpg"))); // NOI18N
        getContentPane().add(backgroundImgLbl);
        backgroundImgLbl.setBounds(0, 0, 400, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatBtnActionPerformed
        // TODO add your handling code here:

        ProjectGUI myProjectGUI= new ProjectGUI();
        StatsGUI myStatsGUI= new StatsGUI();
        myStatsGUI.setVisible(true);
        ProjectGUI.this.setVisible(false);
        
    }//GEN-LAST:event_StatBtnActionPerformed

    private void StatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StatBtnMouseClicked

    private void TriviaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriviaBtnActionPerformed
        // TODO add your handling code here:
        ProjectGUI myProjectGUI= new ProjectGUI();
        TriviaFrame myTrivia= new TriviaFrame();
        myTrivia.setVisible(true);
        ProjectGUI.this.setVisible(false);
    }//GEN-LAST:event_TriviaBtnActionPerformed

    private void InfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBtnActionPerformed
        // TODO add your handling code here:
        ProjectGUI myProjectGUI= new ProjectGUI();
        InfoFrame myInfo= new InfoFrame();
        myInfo.setVisible(true);
        ProjectGUI.this.setVisible(false);
    }//GEN-LAST:event_InfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoBtn;
    private javax.swing.JButton StatBtn;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleBackground;
    private javax.swing.JButton TriviaBtn;
    private javax.swing.JLabel backgroundImgLbl;
    private javax.swing.JLabel jerseyLbl;
    private javax.swing.JLabel stadiumLbl;
    private javax.swing.JLabel triviaLbl;
    // End of variables declaration//GEN-END:variables
}
