/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectGUI;

/**
 *
 * @author x13564737
 */
public class StatsGUI extends javax.swing.JFrame {

    /**
     * Creates new form StatsGUI
     */
    public StatsGUI() {
        initComponents();
        NZrankLbl.setVisible(false);
        NZteamStatsLbl.setVisible(false);
        NZplayer1Lbl.setVisible(false);
        NZplayer2Lbl.setVisible(false);
        NZplayer3Lbl.setVisible(false);
        WrankLbl.setVisible(false);
        WteamStatsLbl.setVisible(false);
        Wplayer1Lbl.setVisible(false);
        Wplayer2Lbl.setVisible(false);
        Wplayer3Lbl.setVisible(false);
        FRrankLbl.setVisible(false);
        FRteamStatsLbl.setVisible(false);
        FRplayer1Lbl.setVisible(false);
        FRplayer2Lbl.setVisible(false);
        FRplayer3Lbl.setVisible(false);
        IErankLbl.setVisible(false);
        IEteamStatsLbl.setVisible(false);
        IEplayer1Lbl.setVisible(false);
        IEplayer2Lbl.setVisible(false);
        IEplayer3Lbl.setVisible(false);
        SArankLbl.setVisible(false);
        SAteamStatsLbl.setVisible(false);
        SAplayer1Lbl.setVisible(false);
        SAplayer2Lbl.setVisible(false);
        SAplayer3Lbl.setVisible(false);
        notice1Lbl.setVisible(true);
        notice2Lbl.setVisible(true);
        noticeBgLbl.setVisible(true);
        noticeBg2Lbl.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamBtnGroup = new javax.swing.ButtonGroup();
        welshFlagLbl = new javax.swing.JLabel();
        newzealandFlagLbl = new javax.swing.JLabel();
        irishFlagLbl = new javax.swing.JLabel();
        notice1Lbl = new javax.swing.JLabel();
        notice2Lbl = new javax.swing.JLabel();
        noticeBgLbl = new javax.swing.JLabel();
        noticeBg2Lbl = new javax.swing.JLabel();
        NZrankLbl = new javax.swing.JLabel();
        NZteamStatsLbl = new javax.swing.JLabel();
        NZplayer1Lbl = new javax.swing.JLabel();
        NZplayer2Lbl = new javax.swing.JLabel();
        NZplayer3Lbl = new javax.swing.JLabel();
        WrankLbl = new javax.swing.JLabel();
        WteamStatsLbl = new javax.swing.JLabel();
        Wplayer1Lbl = new javax.swing.JLabel();
        Wplayer2Lbl = new javax.swing.JLabel();
        Wplayer3Lbl = new javax.swing.JLabel();
        IErankLbl = new javax.swing.JLabel();
        IEteamStatsLbl = new javax.swing.JLabel();
        IEplayer1Lbl = new javax.swing.JLabel();
        IEplayer2Lbl = new javax.swing.JLabel();
        IEplayer3Lbl = new javax.swing.JLabel();
        SArankLbl = new javax.swing.JLabel();
        SAteamStatsLbl = new javax.swing.JLabel();
        SAplayer1Lbl = new javax.swing.JLabel();
        SAplayer2Lbl = new javax.swing.JLabel();
        SAplayer3Lbl = new javax.swing.JLabel();
        FRrankLbl = new javax.swing.JLabel();
        FRteamStatsLbl = new javax.swing.JLabel();
        FRplayer1Lbl = new javax.swing.JLabel();
        FRplayer2Lbl = new javax.swing.JLabel();
        FRplayer3Lbl = new javax.swing.JLabel();
        franceRBtn = new javax.swing.JRadioButton();
        frenchFlagLbl = new javax.swing.JLabel();
        walesRBtn = new javax.swing.JRadioButton();
        irelandRBtn = new javax.swing.JRadioButton();
        southAfricaRBtn = new javax.swing.JRadioButton();
        southafricanFlagLbl = new javax.swing.JLabel();
        newZealandRBtn = new javax.swing.JRadioButton();
        HomeBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 620));
        getContentPane().setLayout(null);

        welshFlagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/wales.gif"))); // NOI18N
        welshFlagLbl.setText("jLabel1");
        getContentPane().add(welshFlagLbl);
        welshFlagLbl.setBounds(310, 250, 80, 40);

        newzealandFlagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/allblackflag.png"))); // NOI18N
        newzealandFlagLbl.setText("jLabel1");
        getContentPane().add(newzealandFlagLbl);
        newzealandFlagLbl.setBounds(60, 150, 80, 40);

        irishFlagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/irishflag.jpg"))); // NOI18N
        getContentPane().add(irishFlagLbl);
        irishFlagLbl.setBounds(310, 200, 80, 40);

        notice1Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        notice1Lbl.setForeground(new java.awt.Color(51, 51, 51));
        notice1Lbl.setText("Click a button to");
        getContentPane().add(notice1Lbl);
        notice1Lbl.setBounds(100, 370, 160, 30);

        notice2Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        notice2Lbl.setText("see Team Stats");
        getContentPane().add(notice2Lbl);
        notice2Lbl.setBounds(130, 400, 130, 20);

        noticeBgLbl.setOpaque(true);
        getContentPane().add(noticeBgLbl);
        noticeBgLbl.setBounds(80, 340, 230, 120);

        noticeBg2Lbl.setBackground(new java.awt.Color(153, 255, 0));
        noticeBg2Lbl.setOpaque(true);
        getContentPane().add(noticeBg2Lbl);
        noticeBg2Lbl.setBounds(70, 330, 250, 140);

        NZrankLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NZrankLbl.setText("Team Stats: NZ's Biggest win etc.");
        NZrankLbl.setOpaque(true);
        getContentPane().add(NZrankLbl);
        NZrankLbl.setBounds(60, 380, 250, 30);

        NZteamStatsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NZteamStatsLbl.setText("World Ranking: 1");
        NZteamStatsLbl.setOpaque(true);
        getContentPane().add(NZteamStatsLbl);
        NZteamStatsLbl.setBounds(60, 330, 250, 30);

        NZplayer1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NZplayer1Lbl.setText("Player 1: Best NZ player");
        NZplayer1Lbl.setOpaque(true);
        getContentPane().add(NZplayer1Lbl);
        NZplayer1Lbl.setBounds(60, 430, 250, 30);

        NZplayer2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NZplayer2Lbl.setText("Player 2: 2nd Best NZ player");
        NZplayer2Lbl.setOpaque(true);
        getContentPane().add(NZplayer2Lbl);
        NZplayer2Lbl.setBounds(60, 480, 250, 30);

        NZplayer3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NZplayer3Lbl.setText("Player 3: 3rd Best NZ player");
        NZplayer3Lbl.setOpaque(true);
        getContentPane().add(NZplayer3Lbl);
        NZplayer3Lbl.setBounds(60, 530, 250, 30);

        WrankLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WrankLbl.setText("World Ranking: 6");
        WrankLbl.setOpaque(true);
        getContentPane().add(WrankLbl);
        WrankLbl.setBounds(60, 330, 250, 30);

        WteamStatsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WteamStatsLbl.setText("Team Stats: Wales' Biggest win etc.");
        WteamStatsLbl.setOpaque(true);
        getContentPane().add(WteamStatsLbl);
        WteamStatsLbl.setBounds(60, 380, 250, 30);

        Wplayer1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Wplayer1Lbl.setText("Player 1: Best Welsh player");
        Wplayer1Lbl.setOpaque(true);
        getContentPane().add(Wplayer1Lbl);
        Wplayer1Lbl.setBounds(60, 430, 250, 30);

        Wplayer2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Wplayer2Lbl.setText("Player 2: 2nd Best Welsh player");
        Wplayer2Lbl.setOpaque(true);
        getContentPane().add(Wplayer2Lbl);
        Wplayer2Lbl.setBounds(60, 480, 250, 30);

        Wplayer3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Wplayer3Lbl.setText("Player 3: 3rd Best Irish player");
        Wplayer3Lbl.setOpaque(true);
        getContentPane().add(Wplayer3Lbl);
        Wplayer3Lbl.setBounds(60, 530, 250, 30);

        IErankLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IErankLbl.setText("World Ranking: 5");
        IErankLbl.setOpaque(true);
        getContentPane().add(IErankLbl);
        IErankLbl.setBounds(60, 330, 250, 30);

        IEteamStatsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IEteamStatsLbl.setText("Team Stats: IE's Biggest win etc.");
        IEteamStatsLbl.setOpaque(true);
        getContentPane().add(IEteamStatsLbl);
        IEteamStatsLbl.setBounds(60, 380, 250, 30);

        IEplayer1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IEplayer1Lbl.setText("Player 1: Best Irish player");
        IEplayer1Lbl.setOpaque(true);
        getContentPane().add(IEplayer1Lbl);
        IEplayer1Lbl.setBounds(60, 430, 250, 30);

        IEplayer2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IEplayer2Lbl.setText("Player 2: 2nd Best Irish player");
        IEplayer2Lbl.setOpaque(true);
        getContentPane().add(IEplayer2Lbl);
        IEplayer2Lbl.setBounds(60, 480, 250, 30);

        IEplayer3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IEplayer3Lbl.setText("Player 3: 3rd Best Irish player");
        IEplayer3Lbl.setOpaque(true);
        getContentPane().add(IEplayer3Lbl);
        IEplayer3Lbl.setBounds(60, 530, 250, 30);

        SArankLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SArankLbl.setText("World Ranking: 2");
        SArankLbl.setOpaque(true);
        getContentPane().add(SArankLbl);
        SArankLbl.setBounds(60, 330, 250, 30);

        SAteamStatsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SAteamStatsLbl.setText("Team Stats: SA's Biggest win etc.");
        SAteamStatsLbl.setOpaque(true);
        getContentPane().add(SAteamStatsLbl);
        SAteamStatsLbl.setBounds(60, 380, 250, 30);

        SAplayer1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SAplayer1Lbl.setText("Player 1: Best SA player");
        SAplayer1Lbl.setOpaque(true);
        getContentPane().add(SAplayer1Lbl);
        SAplayer1Lbl.setBounds(60, 430, 250, 30);

        SAplayer2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SAplayer2Lbl.setText("Player 2: 2nd Best SA player");
        SAplayer2Lbl.setOpaque(true);
        getContentPane().add(SAplayer2Lbl);
        SAplayer2Lbl.setBounds(60, 480, 250, 30);

        SAplayer3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SAplayer3Lbl.setText("Player 3: 3rd Best SA player");
        SAplayer3Lbl.setOpaque(true);
        getContentPane().add(SAplayer3Lbl);
        SAplayer3Lbl.setBounds(60, 530, 250, 30);

        FRrankLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FRrankLbl.setText("World Ranking: 7");
        FRrankLbl.setOpaque(true);
        getContentPane().add(FRrankLbl);
        FRrankLbl.setBounds(60, 330, 250, 30);

        FRteamStatsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FRteamStatsLbl.setText("Team Stats: FR's Biggest win etc.");
        FRteamStatsLbl.setOpaque(true);
        getContentPane().add(FRteamStatsLbl);
        FRteamStatsLbl.setBounds(60, 380, 250, 30);

        FRplayer1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FRplayer1Lbl.setText("Player 1: Best French player");
        FRplayer1Lbl.setOpaque(true);
        getContentPane().add(FRplayer1Lbl);
        FRplayer1Lbl.setBounds(60, 430, 250, 30);

        FRplayer2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FRplayer2Lbl.setText("Player 2: 2nd Best French player");
        FRplayer2Lbl.setOpaque(true);
        getContentPane().add(FRplayer2Lbl);
        FRplayer2Lbl.setBounds(60, 480, 250, 30);

        FRplayer3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FRplayer3Lbl.setText("Player 3: 3rd Best French player");
        FRplayer3Lbl.setOpaque(true);
        getContentPane().add(FRplayer3Lbl);
        FRplayer3Lbl.setBounds(60, 530, 250, 30);

        teamBtnGroup.add(franceRBtn);
        franceRBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        franceRBtn.setForeground(new java.awt.Color(0, 51, 255));
        franceRBtn.setText("France");
        franceRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                franceRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(franceRBtn);
        franceRBtn.setBounds(60, 200, 110, 40);

        frenchFlagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/frenchflag.gif"))); // NOI18N
        frenchFlagLbl.setText("gfj");
        getContentPane().add(frenchFlagLbl);
        frenchFlagLbl.setBounds(0, 200, 80, 40);

        teamBtnGroup.add(walesRBtn);
        walesRBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        walesRBtn.setForeground(new java.awt.Color(255, 51, 0));
        walesRBtn.setText("Wales");
        walesRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walesRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(walesRBtn);
        walesRBtn.setBounds(240, 250, 90, 40);

        teamBtnGroup.add(irelandRBtn);
        irelandRBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        irelandRBtn.setForeground(new java.awt.Color(0, 153, 51));
        irelandRBtn.setText("Ireland");
        irelandRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irelandRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(irelandRBtn);
        irelandRBtn.setBounds(240, 200, 90, 40);

        teamBtnGroup.add(southAfricaRBtn);
        southAfricaRBtn.setForeground(new java.awt.Color(153, 153, 0));
        southAfricaRBtn.setText("South Africa");
        southAfricaRBtn.setBorder(null);
        southAfricaRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southAfricaRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(southAfricaRBtn);
        southAfricaRBtn.setBounds(60, 250, 110, 40);

        southafricanFlagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/southafricanflag.gif"))); // NOI18N
        getContentPane().add(southafricanFlagLbl);
        southafricanFlagLbl.setBounds(0, 250, 80, 40);

        teamBtnGroup.add(newZealandRBtn);
        newZealandRBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        newZealandRBtn.setText("New Zealand");
        newZealandRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newZealandRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newZealandRBtn);
        newZealandRBtn.setBounds(140, 150, 110, 40);

        HomeBtn.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn);
        HomeBtn.setBounds(10, 10, 80, 30);

        titleLbl.setBackground(new java.awt.Color(0, 153, 153));
        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText(" Player + Team Stats");
        titleLbl.setOpaque(true);
        getContentPane().add(titleLbl);
        titleLbl.setBounds(40, 50, 310, 60);
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        
    private void irelandRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irelandRBtnActionPerformed
        // TODO add your handling code here:
        NZrankLbl.setVisible(false);
        NZteamStatsLbl.setVisible(false);
        NZplayer1Lbl.setVisible(false);
        NZplayer2Lbl.setVisible(false);
        NZplayer3Lbl.setVisible(false);
        WrankLbl.setVisible(false);
        WteamStatsLbl.setVisible(false);
        Wplayer1Lbl.setVisible(false);
        Wplayer2Lbl.setVisible(false);
        Wplayer3Lbl.setVisible(false);
        FRrankLbl.setVisible(false);
        FRteamStatsLbl.setVisible(false);
        FRplayer1Lbl.setVisible(false);
        FRplayer2Lbl.setVisible(false);
        FRplayer3Lbl.setVisible(false);
        IErankLbl.setVisible(true);
        IEteamStatsLbl.setVisible(true);
        IEplayer1Lbl.setVisible(true);
        IEplayer2Lbl.setVisible(true);
        IEplayer3Lbl.setVisible(true);
        SArankLbl.setVisible(false);
        SAteamStatsLbl.setVisible(false);
        SAplayer1Lbl.setVisible(false);
        SAplayer2Lbl.setVisible(false);
        SAplayer3Lbl.setVisible(false);
        notice1Lbl.setVisible(false);
        notice2Lbl.setVisible(false);
        noticeBgLbl.setVisible(false);
        noticeBg2Lbl.setVisible(false);
    }//GEN-LAST:event_irelandRBtnActionPerformed

    private void southAfricaRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southAfricaRBtnActionPerformed
        // TODO add your handling code here:
        NZrankLbl.setVisible(false);
        NZteamStatsLbl.setVisible(false);
        NZplayer1Lbl.setVisible(false);
        NZplayer2Lbl.setVisible(false);
        NZplayer3Lbl.setVisible(false);
        WrankLbl.setVisible(false);
        WteamStatsLbl.setVisible(false);
        Wplayer1Lbl.setVisible(false);
        Wplayer2Lbl.setVisible(false);
        Wplayer3Lbl.setVisible(false);
        FRrankLbl.setVisible(false);
        FRteamStatsLbl.setVisible(false);
        FRplayer1Lbl.setVisible(false);
        FRplayer2Lbl.setVisible(false);
        FRplayer3Lbl.setVisible(false);
        IErankLbl.setVisible(false);
        IEteamStatsLbl.setVisible(false);
        IEplayer1Lbl.setVisible(false);
        IEplayer2Lbl.setVisible(false);
        IEplayer3Lbl.setVisible(false);
        SArankLbl.setVisible(true);
        SAteamStatsLbl.setVisible(true);
        SAplayer1Lbl.setVisible(true);
        SAplayer2Lbl.setVisible(true);
        SAplayer3Lbl.setVisible(true);
        notice1Lbl.setVisible(false);
        notice2Lbl.setVisible(false);
        noticeBgLbl.setVisible(false);
        noticeBg2Lbl.setVisible(false);
        
    }//GEN-LAST:event_southAfricaRBtnActionPerformed

    private void walesRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walesRBtnActionPerformed
        // TODO add your handling code here:
        NZrankLbl.setVisible(false);
        NZteamStatsLbl.setVisible(false);
        NZplayer1Lbl.setVisible(false);
        NZplayer2Lbl.setVisible(false);
        NZplayer3Lbl.setVisible(false);
        WrankLbl.setVisible(true);
        WteamStatsLbl.setVisible(true);
        Wplayer1Lbl.setVisible(true);
        Wplayer2Lbl.setVisible(true);
        Wplayer3Lbl.setVisible(true);
        FRrankLbl.setVisible(false);
        FRteamStatsLbl.setVisible(false);
        FRplayer1Lbl.setVisible(false);
        FRplayer2Lbl.setVisible(false);
        FRplayer3Lbl.setVisible(false);
        IErankLbl.setVisible(false);
        IEteamStatsLbl.setVisible(false);
        IEplayer1Lbl.setVisible(false);
        IEplayer2Lbl.setVisible(false);
        IEplayer3Lbl.setVisible(false);
        SArankLbl.setVisible(false);
        SAteamStatsLbl.setVisible(false);
        SAplayer1Lbl.setVisible(false);
        SAplayer2Lbl.setVisible(false);
        SAplayer3Lbl.setVisible(false);
        notice1Lbl.setVisible(false);
        notice2Lbl.setVisible(false);
        noticeBgLbl.setVisible(false);
        noticeBg2Lbl.setVisible(false);
        
    }//GEN-LAST:event_walesRBtnActionPerformed

    private void franceRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_franceRBtnActionPerformed
        // TODO add your handling code here:
        NZrankLbl.setVisible(false);
        NZteamStatsLbl.setVisible(false);
        NZplayer1Lbl.setVisible(false);
        NZplayer2Lbl.setVisible(false);
        NZplayer3Lbl.setVisible(false);
        WrankLbl.setVisible(false);
        WteamStatsLbl.setVisible(false);
        Wplayer1Lbl.setVisible(false);
        Wplayer2Lbl.setVisible(false);
        Wplayer3Lbl.setVisible(false);
        FRrankLbl.setVisible(true);
        FRteamStatsLbl.setVisible(true);
        FRplayer1Lbl.setVisible(true);
        FRplayer2Lbl.setVisible(true);
        FRplayer3Lbl.setVisible(true);
        IErankLbl.setVisible(false);
        IEteamStatsLbl.setVisible(false);
        IEplayer1Lbl.setVisible(false);
        IEplayer2Lbl.setVisible(false);
        IEplayer3Lbl.setVisible(false);
        SArankLbl.setVisible(false);
        SAteamStatsLbl.setVisible(false);
        SAplayer1Lbl.setVisible(false);
        SAplayer2Lbl.setVisible(false);
        SAplayer3Lbl.setVisible(false);
        notice1Lbl.setVisible(false);
        notice2Lbl.setVisible(false);
        noticeBgLbl.setVisible(false);
        noticeBg2Lbl.setVisible(false);
        
    }//GEN-LAST:event_franceRBtnActionPerformed

    private void newZealandRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newZealandRBtnActionPerformed
        // TODO add your handling code here:
        NZrankLbl.setVisible(true);
        NZteamStatsLbl.setVisible(true);
        NZplayer1Lbl.setVisible(true);
        NZplayer2Lbl.setVisible(true);
        NZplayer3Lbl.setVisible(true);
        WrankLbl.setVisible(false);
        WteamStatsLbl.setVisible(false);
        Wplayer1Lbl.setVisible(false);
        Wplayer2Lbl.setVisible(false);
        Wplayer3Lbl.setVisible(false);
        FRrankLbl.setVisible(false);
        FRteamStatsLbl.setVisible(false);
        FRplayer1Lbl.setVisible(false);
        FRplayer2Lbl.setVisible(false);
        FRplayer3Lbl.setVisible(false);
        IErankLbl.setVisible(false);
        IEteamStatsLbl.setVisible(false);
        IEplayer1Lbl.setVisible(false);
        IEplayer2Lbl.setVisible(false);
        IEplayer3Lbl.setVisible(false);
        SArankLbl.setVisible(false);
        SAteamStatsLbl.setVisible(false);
        SAplayer1Lbl.setVisible(false);
        SAplayer2Lbl.setVisible(false);
        SAplayer3Lbl.setVisible(false);
        notice1Lbl.setVisible(false);
        notice2Lbl.setVisible(false);
        noticeBgLbl.setVisible(false);
        noticeBg2Lbl.setVisible(false);
        
    }//GEN-LAST:event_newZealandRBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        ProjectGUI myProjectGUI= new ProjectGUI();
        myProjectGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatsGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FRplayer1Lbl;
    private javax.swing.JLabel FRplayer2Lbl;
    private javax.swing.JLabel FRplayer3Lbl;
    private javax.swing.JLabel FRrankLbl;
    private javax.swing.JLabel FRteamStatsLbl;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel IEplayer1Lbl;
    private javax.swing.JLabel IEplayer2Lbl;
    private javax.swing.JLabel IEplayer3Lbl;
    private javax.swing.JLabel IErankLbl;
    private javax.swing.JLabel IEteamStatsLbl;
    private javax.swing.JLabel NZplayer1Lbl;
    private javax.swing.JLabel NZplayer2Lbl;
    private javax.swing.JLabel NZplayer3Lbl;
    private javax.swing.JLabel NZrankLbl;
    private javax.swing.JLabel NZteamStatsLbl;
    private javax.swing.JLabel SAplayer1Lbl;
    private javax.swing.JLabel SAplayer2Lbl;
    private javax.swing.JLabel SAplayer3Lbl;
    private javax.swing.JLabel SArankLbl;
    private javax.swing.JLabel SAteamStatsLbl;
    private javax.swing.JLabel Wplayer1Lbl;
    private javax.swing.JLabel Wplayer2Lbl;
    private javax.swing.JLabel Wplayer3Lbl;
    private javax.swing.JLabel WrankLbl;
    private javax.swing.JLabel WteamStatsLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JRadioButton franceRBtn;
    private javax.swing.JLabel frenchFlagLbl;
    private javax.swing.JRadioButton irelandRBtn;
    private javax.swing.JLabel irishFlagLbl;
    private javax.swing.JRadioButton newZealandRBtn;
    private javax.swing.JLabel newzealandFlagLbl;
    private javax.swing.JLabel notice1Lbl;
    private javax.swing.JLabel notice2Lbl;
    private javax.swing.JLabel noticeBg2Lbl;
    private javax.swing.JLabel noticeBgLbl;
    private javax.swing.JRadioButton southAfricaRBtn;
    private javax.swing.JLabel southafricanFlagLbl;
    private javax.swing.ButtonGroup teamBtnGroup;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JRadioButton walesRBtn;
    private javax.swing.JLabel welshFlagLbl;
    // End of variables declaration//GEN-END:variables
}
