package ProjectGUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x13332576
 */
public class TriviaFrame extends javax.swing.JFrame{
        private int correctA;
        private int wrongA;
        private int count;
        private String name;
        ArrayList <Trivia> ql;
        
    /**
     * Creates new form TriviaFrame
     */
    public TriviaFrame() {
        initComponents();
     
        name = new String();
        ql = new ArrayList<>();
        correctA = 0;
        
        Score1.setVisible(false);
        NameLbl.setVisible(false);
        EnterBtn.setVisible(false);
        NameTF.setVisible(false);
        conGrts.setVisible(false);
        SaveBtn.setVisible(false);

      
        //Current Question
        CurrentQLbl1.setVisible(false);
        CurrentQLbl2.setVisible(false);
        CurrentQLbl3.setVisible(false);
        CurrentQLbl4.setVisible(false);
        CurrentQLbl5.setVisible(false);
        CurrentQLbl6.setVisible(false);
        CurrentQLbl7.setVisible(false);
        CurrentQLbl8.setVisible(false);
        CurrentQLbl9.setVisible(false);
        
        //Question Headings
        qLbl1.setVisible(false);
        qLbl2.setVisible(false);
        qLbl3.setVisible(false);
        qLbl4.setVisible(false);
        qLbl5.setVisible(false);
        qLbl6.setVisible(false);
        qLbl7.setVisible(false);
        qLbl8.setVisible(false);
        
        //Questions
        QuestionLbl1.setVisible(false);
        QuestionLbl2.setVisible(false);
        QuestionLbl3.setVisible(false);
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(false);
        QuestionLbl6.setVisible(false);
        QuestionLbl7.setVisible(false);
        QuestionLbl8.setVisible(false);
        QuestionLbl9.setVisible(false);
        
        PicQ1.setVisible(false);
        PicQ2.setVisible(false);
        
        RestartBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        BackgroundLbl = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        CurrentQLbl = new javax.swing.JLabel();
        CurrentQLbl1 = new javax.swing.JLabel();
        CurrentQLbl2 = new javax.swing.JLabel();
        CurrentQLbl3 = new javax.swing.JLabel();
        CurrentQLbl4 = new javax.swing.JLabel();
        CurrentQLbl5 = new javax.swing.JLabel();
        CurrentQLbl6 = new javax.swing.JLabel();
        CurrentQLbl7 = new javax.swing.JLabel();
        CurrentQLbl8 = new javax.swing.JLabel();
        CurrentQLbl9 = new javax.swing.JLabel();
        qLbl = new javax.swing.JLabel();
        qLbl1 = new javax.swing.JLabel();
        qLbl2 = new javax.swing.JLabel();
        qLbl3 = new javax.swing.JLabel();
        qLbl4 = new javax.swing.JLabel();
        qLbl5 = new javax.swing.JLabel();
        qLbl6 = new javax.swing.JLabel();
        qLbl7 = new javax.swing.JLabel();
        qLbl8 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JToggleButton();
        DisplayBtn = new javax.swing.JButton();
        Score2 = new javax.swing.JLabel();
        Score1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        conGrts = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        EnterBtn = new javax.swing.JButton();
        QuestionLbl = new javax.swing.JLabel();
        QuestionLbl1 = new javax.swing.JLabel();
        QuestionLbl2 = new javax.swing.JLabel();
        QuestionLbl3 = new javax.swing.JLabel();
        QuestionLbl4 = new javax.swing.JLabel();
        QuestionLbl5 = new javax.swing.JLabel();
        QuestionLbl6 = new javax.swing.JLabel();
        QuestionLbl7 = new javax.swing.JLabel();
        QuestionLbl8 = new javax.swing.JLabel();
        QuestionLbl9 = new javax.swing.JLabel();
        PicQ1 = new javax.swing.JLabel();
        PicQ2 = new javax.swing.JLabel();
        ScoreArea = new javax.swing.JPanel();
        QuestionArea = new javax.swing.JPanel();
        option1 = new javax.swing.JButton();
        option5 = new javax.swing.JButton();
        option9 = new javax.swing.JButton();
        option13 = new javax.swing.JButton();
        option17 = new javax.swing.JButton();
        option21 = new javax.swing.JButton();
        option25 = new javax.swing.JButton();
        option29 = new javax.swing.JButton();
        option33 = new javax.swing.JButton();
        option37 = new javax.swing.JButton();
        option2 = new javax.swing.JButton();
        option6 = new javax.swing.JButton();
        option10 = new javax.swing.JButton();
        option14 = new javax.swing.JButton();
        option18 = new javax.swing.JButton();
        option22 = new javax.swing.JButton();
        option26 = new javax.swing.JButton();
        option30 = new javax.swing.JButton();
        option34 = new javax.swing.JButton();
        option38 = new javax.swing.JButton();
        option3 = new javax.swing.JButton();
        option7 = new javax.swing.JButton();
        option11 = new javax.swing.JButton();
        option15 = new javax.swing.JButton();
        option19 = new javax.swing.JButton();
        option23 = new javax.swing.JButton();
        option27 = new javax.swing.JButton();
        option31 = new javax.swing.JButton();
        option35 = new javax.swing.JButton();
        option39 = new javax.swing.JButton();
        option4 = new javax.swing.JButton();
        option8 = new javax.swing.JButton();
        option12 = new javax.swing.JButton();
        option16 = new javax.swing.JButton();
        option20 = new javax.swing.JButton();
        option24 = new javax.swing.JButton();
        option28 = new javax.swing.JButton();
        option32 = new javax.swing.JButton();
        option36 = new javax.swing.JButton();
        option40 = new javax.swing.JButton();
        RestartBtn = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jButton3.setText("jButton3");

        BackgroundLbl.setText("jLabel7");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(456, 665));
        getContentPane().setLayout(null);

        CurrentQLbl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl.setText("Question 1/10");
        getContentPane().add(CurrentQLbl);
        CurrentQLbl.setBounds(360, 360, 70, 15);

        CurrentQLbl1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl1.setText("Question 2/10");
        getContentPane().add(CurrentQLbl1);
        CurrentQLbl1.setBounds(360, 360, 70, 15);

        CurrentQLbl2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl2.setText("Question 3/10");
        getContentPane().add(CurrentQLbl2);
        CurrentQLbl2.setBounds(360, 360, 70, 15);

        CurrentQLbl3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl3.setText("Question 4/10");
        getContentPane().add(CurrentQLbl3);
        CurrentQLbl3.setBounds(360, 360, 70, 15);

        CurrentQLbl4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl4.setText("Question 5/10");
        getContentPane().add(CurrentQLbl4);
        CurrentQLbl4.setBounds(360, 360, 70, 15);

        CurrentQLbl5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl5.setText("Question 6/10");
        getContentPane().add(CurrentQLbl5);
        CurrentQLbl5.setBounds(360, 360, 70, 15);

        CurrentQLbl6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl6.setText("Question 7/10");
        getContentPane().add(CurrentQLbl6);
        CurrentQLbl6.setBounds(360, 360, 70, 15);

        CurrentQLbl7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl7.setText("Question 8/10");
        getContentPane().add(CurrentQLbl7);
        CurrentQLbl7.setBounds(360, 360, 70, 15);

        CurrentQLbl8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl8.setText("Question 9/10");
        getContentPane().add(CurrentQLbl8);
        CurrentQLbl8.setBounds(360, 360, 70, 15);

        CurrentQLbl9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CurrentQLbl9.setText("Question 10/10");
        getContentPane().add(CurrentQLbl9);
        CurrentQLbl9.setBounds(360, 360, 80, 15);

        qLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl.setText("Question 1");
        getContentPane().add(qLbl);
        qLbl.setBounds(40, 210, 80, 30);

        qLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl1.setText("Question 2");
        getContentPane().add(qLbl1);
        qLbl1.setBounds(40, 210, 80, 30);

        qLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl2.setText("Question 3");
        getContentPane().add(qLbl2);
        qLbl2.setBounds(40, 210, 80, 30);

        qLbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl3.setText("Question 4");
        getContentPane().add(qLbl3);
        qLbl3.setBounds(40, 210, 80, 30);

        qLbl4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl4.setText("Question 6");
        getContentPane().add(qLbl4);
        qLbl4.setBounds(40, 210, 80, 30);

        qLbl5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl5.setText("Question 7");
        getContentPane().add(qLbl5);
        qLbl5.setBounds(40, 210, 80, 30);

        qLbl6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl6.setText("Question 8");
        qLbl6.setToolTipText("");
        getContentPane().add(qLbl6);
        qLbl6.setBounds(40, 210, 80, 30);

        qLbl7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl7.setText("Question 9");
        qLbl7.setToolTipText("");
        getContentPane().add(qLbl7);
        qLbl7.setBounds(40, 210, 80, 30);

        qLbl8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qLbl8.setText("Question 10");
        qLbl8.setToolTipText("");
        getContentPane().add(qLbl8);
        qLbl8.setBounds(40, 210, 80, 30);

        HomeBtn.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtn.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn);
        HomeBtn.setBounds(10, 10, 90, 40);

        DisplayBtn.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        DisplayBtn.setText("Show Scores");
        DisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayBtn);
        DisplayBtn.setBounds(353, 140, 80, 23);

        Score2.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        Score2.setText("Last Score");
        getContentPane().add(Score2);
        Score2.setBounds(360, 190, 60, 15);

        Score1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        Score1.setText("x");
        getContentPane().add(Score1);
        Score1.setBounds(370, 215, 60, 15);

        Title.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/icon2.png"))); // NOI18N
        Title.setText("Trivia");
        getContentPane().add(Title);
        Title.setBounds(160, -20, 200, 210);

        conGrts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        conGrts.setText("Well Done!");
        getContentPane().add(conGrts);
        conGrts.setBounds(110, 170, 80, 30);

        NameLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        NameLbl.setText("Name: ");
        getContentPane().add(NameLbl);
        NameLbl.setBounds(80, 220, 50, 20);

        NameTF.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        getContentPane().add(NameTF);
        NameTF.setBounds(120, 220, 110, 20);

        SaveBtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(180, 260, 110, 50);

        EnterBtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        EnterBtn.setText("Finish");
        EnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EnterBtn);
        EnterBtn.setBounds(60, 260, 100, 50);

        QuestionLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl.setText("Who won the rugby world cup in 1987?");
        getContentPane().add(QuestionLbl);
        QuestionLbl.setBounds(40, 210, 270, 140);

        QuestionLbl1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl1.setText("Who is the captain of the Irish rugby team?");
        getContentPane().add(QuestionLbl1);
        QuestionLbl1.setBounds(40, 210, 270, 140);

        QuestionLbl2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl2.setText("What is the name of the cup awarded to the winners?");
        getContentPane().add(QuestionLbl2);
        QuestionLbl2.setBounds(40, 210, 270, 140);

        QuestionLbl3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl3.setText("How many teams will be in this coming tournament?");
        getContentPane().add(QuestionLbl3);
        QuestionLbl3.setBounds(40, 210, 270, 140);

        QuestionLbl4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl4.setText("Guess who?");
        getContentPane().add(QuestionLbl4);
        QuestionLbl4.setBounds(50, 320, 270, 140);

        QuestionLbl5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl5.setText("Who is the top try scorer in Celtic league history? ");
        getContentPane().add(QuestionLbl5);
        QuestionLbl5.setBounds(40, 210, 270, 140);

        QuestionLbl6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl6.setText("Name the stadium in the picture.");
        getContentPane().add(QuestionLbl6);
        QuestionLbl6.setBounds(50, 320, 270, 140);

        QuestionLbl7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl7.setText("Which Six nations team has won the most titles?");
        getContentPane().add(QuestionLbl7);
        QuestionLbl7.setBounds(40, 210, 270, 140);

        QuestionLbl8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl8.setText("Who was named player of the 2012 Six Nations?");
        getContentPane().add(QuestionLbl8);
        QuestionLbl8.setBounds(40, 210, 270, 140);

        QuestionLbl9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        QuestionLbl9.setText("How many times have Ireland won the Grand Slam?");
        getContentPane().add(QuestionLbl9);
        QuestionLbl9.setBounds(40, 210, 270, 140);

        PicQ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/guess.jpg"))); // NOI18N
        PicQ1.setToolTipText("");
        getContentPane().add(PicQ1);
        PicQ1.setBounds(50, 150, 220, 220);

        PicQ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/wembleySmall.jpg"))); // NOI18N
        PicQ2.setToolTipText("");
        getContentPane().add(PicQ2);
        PicQ2.setBounds(50, 150, 220, 220);

        ScoreArea.setBackground(new java.awt.Color(0, 204, 204));
        ScoreArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ScoreArea);
        ScoreArea.setBounds(350, 130, 90, 300);

        QuestionArea.setBackground(new java.awt.Color(0, 204, 204));
        QuestionArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(QuestionArea);
        QuestionArea.setBounds(20, 130, 310, 300);

        option1.setBackground(new java.awt.Color(255, 255, 255));
        option1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option1.setText("New Zeland");
        option1.setBorder(null);
        option1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1ActionPerformed(evt);
            }
        });
        getContentPane().add(option1);
        option1.setBounds(50, 470, 160, 60);

        option5.setBackground(new java.awt.Color(255, 255, 255));
        option5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option5.setText("Rory Best");
        option5.setBorder(null);
        option5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option5ActionPerformed(evt);
            }
        });
        getContentPane().add(option5);
        option5.setBounds(50, 470, 160, 60);

        option9.setBackground(new java.awt.Color(255, 255, 255));
        option9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option9.setText("Jules Rimet Trophy");
        option9.setBorder(null);
        option9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option9ActionPerformed(evt);
            }
        });
        getContentPane().add(option9);
        option9.setBounds(50, 470, 160, 60);

        option13.setBackground(new java.awt.Color(255, 255, 255));
        option13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option13.setText("14");
        option13.setBorder(null);
        option13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option13ActionPerformed(evt);
            }
        });
        getContentPane().add(option13);
        option13.setBounds(50, 470, 160, 60);

        option17.setBackground(new java.awt.Color(255, 255, 255));
        option17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option17.setText("Girvan Dempsey");
        option17.setBorder(null);
        option17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option17ActionPerformed(evt);
            }
        });
        getContentPane().add(option17);
        option17.setBounds(50, 470, 160, 60);

        option21.setBackground(new java.awt.Color(255, 255, 255));
        option21.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option21.setText("Dicky Jeeps");
        option21.setBorder(null);
        option21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option21ActionPerformed(evt);
            }
        });
        getContentPane().add(option21);
        option21.setBounds(50, 470, 160, 60);

        option25.setBackground(new java.awt.Color(255, 255, 255));
        option25.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option25.setText("Wembley ");
        option25.setBorder(null);
        option25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option25ActionPerformed(evt);
            }
        });
        getContentPane().add(option25);
        option25.setBounds(50, 470, 160, 60);

        option29.setBackground(new java.awt.Color(255, 255, 255));
        option29.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option29.setText("France");
        option29.setBorder(null);
        option29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option29ActionPerformed(evt);
            }
        });
        getContentPane().add(option29);
        option29.setBounds(50, 470, 160, 60);

        option33.setBackground(new java.awt.Color(255, 255, 255));
        option33.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option33.setText("Walter Cristofoletto");
        option33.setBorder(null);
        option33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option33ActionPerformed(evt);
            }
        });
        getContentPane().add(option33);
        option33.setBounds(50, 470, 160, 60);

        option37.setBackground(new java.awt.Color(255, 255, 255));
        option37.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option37.setText("4");
        option37.setBorder(null);
        option37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option37ActionPerformed(evt);
            }
        });
        getContentPane().add(option37);
        option37.setBounds(50, 470, 160, 60);

        option2.setBackground(new java.awt.Color(255, 255, 255));
        option2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option2.setText("Wales");
        option2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2ActionPerformed(evt);
            }
        });
        getContentPane().add(option2);
        option2.setBounds(250, 470, 160, 60);

        option6.setBackground(new java.awt.Color(255, 255, 255));
        option6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option6.setText("Paul O'Connel");
        option6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option6ActionPerformed(evt);
            }
        });
        getContentPane().add(option6);
        option6.setBounds(250, 470, 160, 60);

        option10.setBackground(new java.awt.Color(255, 255, 255));
        option10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option10.setText("William Web Ellis");
        option10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option10ActionPerformed(evt);
            }
        });
        getContentPane().add(option10);
        option10.setBounds(250, 470, 160, 60);

        option14.setBackground(new java.awt.Color(255, 255, 255));
        option14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option14.setText("12");
        option14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option14ActionPerformed(evt);
            }
        });
        getContentPane().add(option14);
        option14.setBounds(250, 470, 160, 60);

        option18.setBackground(new java.awt.Color(255, 255, 255));
        option18.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option18.setText("Ronan O'Gara");
        option18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option18ActionPerformed(evt);
            }
        });
        getContentPane().add(option18);
        option18.setBounds(250, 470, 160, 60);

        option22.setBackground(new java.awt.Color(255, 255, 255));
        option22.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option22.setText("John Hayes");
        option22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option22ActionPerformed(evt);
            }
        });
        getContentPane().add(option22);
        option22.setBounds(250, 470, 160, 60);

        option26.setBackground(new java.awt.Color(255, 255, 255));
        option26.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option26.setText("The Aviva");
        option26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option26ActionPerformed(evt);
            }
        });
        getContentPane().add(option26);
        option26.setBounds(250, 470, 160, 60);

        option30.setBackground(new java.awt.Color(255, 255, 255));
        option30.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option30.setText("Italy");
        option30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option30ActionPerformed(evt);
            }
        });
        getContentPane().add(option30);
        option30.setBounds(250, 470, 160, 60);

        option34.setBackground(new java.awt.Color(255, 255, 255));
        option34.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option34.setText("Dan Lydiate");
        option34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option34ActionPerformed(evt);
            }
        });
        getContentPane().add(option34);
        option34.setBounds(250, 470, 160, 60);

        option38.setBackground(new java.awt.Color(255, 255, 255));
        option38.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option38.setText("1");
        option38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option38ActionPerformed(evt);
            }
        });
        getContentPane().add(option38);
        option38.setBounds(250, 470, 160, 60);

        option3.setBackground(new java.awt.Color(255, 255, 255));
        option3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option3.setText("Ireland");
        option3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3ActionPerformed(evt);
            }
        });
        getContentPane().add(option3);
        option3.setBounds(50, 550, 160, 60);

        option7.setBackground(new java.awt.Color(255, 255, 255));
        option7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option7.setText("Johnathan Sexton");
        option7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option7ActionPerformed(evt);
            }
        });
        getContentPane().add(option7);
        option7.setBounds(50, 550, 160, 60);

        option11.setBackground(new java.awt.Color(255, 255, 255));
        option11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option11.setText("Coffee Mug");
        option11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option11ActionPerformed(evt);
            }
        });
        getContentPane().add(option11);
        option11.setBounds(50, 550, 160, 60);

        option15.setBackground(new java.awt.Color(255, 255, 255));
        option15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option15.setText("20");
        option15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option15ActionPerformed(evt);
            }
        });
        getContentPane().add(option15);
        option15.setBounds(50, 550, 160, 60);

        option19.setBackground(new java.awt.Color(255, 255, 255));
        option19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option19.setText("Brian O ' Driscoll");
        option19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option19ActionPerformed(evt);
            }
        });
        getContentPane().add(option19);
        option19.setBounds(50, 550, 160, 60);

        option23.setBackground(new java.awt.Color(255, 255, 255));
        option23.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option23.setText("Reece Lockheart");
        option23.setActionCommand("Reece Lockhart");
        option23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option23ActionPerformed(evt);
            }
        });
        getContentPane().add(option23);
        option23.setBounds(50, 550, 160, 60);

        option27.setBackground(new java.awt.Color(255, 255, 255));
        option27.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option27.setText("Twickenham");
        option27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option27ActionPerformed(evt);
            }
        });
        getContentPane().add(option27);
        option27.setBounds(50, 550, 160, 60);

        option31.setBackground(new java.awt.Color(255, 255, 255));
        option31.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option31.setText("Scotland");
        option31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option31ActionPerformed(evt);
            }
        });
        getContentPane().add(option31);
        option31.setBounds(50, 550, 160, 60);

        option35.setBackground(new java.awt.Color(255, 255, 255));
        option35.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option35.setText("Jake Blackmore");
        option35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option35ActionPerformed(evt);
            }
        });
        getContentPane().add(option35);
        option35.setBounds(50, 550, 160, 60);

        option39.setBackground(new java.awt.Color(255, 255, 255));
        option39.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option39.setText("2");
        option39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option39ActionPerformed(evt);
            }
        });
        getContentPane().add(option39);
        option39.setBounds(50, 550, 160, 60);

        option4.setBackground(new java.awt.Color(255, 255, 255));
        option4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option4.setText("Samoa");
        option4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4ActionPerformed(evt);
            }
        });
        getContentPane().add(option4);
        option4.setBounds(250, 550, 160, 60);

        option8.setBackground(new java.awt.Color(255, 255, 255));
        option8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option8.setText("Jamie Heaslip");
        option8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option8ActionPerformed(evt);
            }
        });
        getContentPane().add(option8);
        option8.setBounds(250, 550, 160, 60);

        option12.setBackground(new java.awt.Color(255, 255, 255));
        option12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option12.setText("The Larry O'Brien");
        option12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option12ActionPerformed(evt);
            }
        });
        getContentPane().add(option12);
        option12.setBounds(250, 550, 160, 60);

        option16.setBackground(new java.awt.Color(255, 255, 255));
        option16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option16.setText("18");
        option16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option16ActionPerformed(evt);
            }
        });
        getContentPane().add(option16);
        option16.setBounds(250, 550, 160, 60);

        option20.setBackground(new java.awt.Color(255, 255, 255));
        option20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option20.setText("Dan Norton");
        option20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option20ActionPerformed(evt);
            }
        });
        getContentPane().add(option20);
        option20.setBounds(250, 550, 160, 60);

        option24.setBackground(new java.awt.Color(255, 255, 255));
        option24.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option24.setText("Tommy Bowe");
        option24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option24ActionPerformed(evt);
            }
        });
        getContentPane().add(option24);
        option24.setBounds(250, 550, 160, 60);

        option28.setBackground(new java.awt.Color(255, 255, 255));
        option28.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option28.setText("Welford Road");
        option28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option28ActionPerformed(evt);
            }
        });
        getContentPane().add(option28);
        option28.setBounds(250, 550, 160, 60);

        option32.setBackground(new java.awt.Color(255, 255, 255));
        option32.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option32.setText("England");
        option32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option32ActionPerformed(evt);
            }
        });
        getContentPane().add(option32);
        option32.setBounds(250, 550, 160, 60);

        option36.setBackground(new java.awt.Color(255, 255, 255));
        option36.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option36.setText("Austin Healey");
        option36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option36ActionPerformed(evt);
            }
        });
        getContentPane().add(option36);
        option36.setBounds(250, 550, 160, 60);

        option40.setBackground(new java.awt.Color(255, 255, 255));
        option40.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        option40.setText("3");
        option40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option40ActionPerformed(evt);
            }
        });
        getContentPane().add(option40);
        option40.setBounds(250, 550, 160, 60);

        RestartBtn.setBackground(new java.awt.Color(255, 255, 255));
        RestartBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        RestartBtn.setText("Restart");
        RestartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RestartBtn);
        RestartBtn.setBounds(150, 510, 160, 60);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectGUI/RugbyWorldCup2011_Hero.JPG"))); // NOI18N
        BackgroundLabel.setText("jLabel2");
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 460, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        ProjectGUI myProjectGUI= new ProjectGUI();
        myProjectGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ActionPerformed
        // TODO add your handling code here:
        correctA++;
        
        //Current Question 
        CurrentQLbl1.setVisible(true);
        CurrentQLbl.setVisible(false);
        
        //Question Headings
        qLbl.setVisible(false);
        qLbl1.setVisible(true);
        
        //Questions
        QuestionLbl.setVisible(false);
        QuestionLbl1.setVisible(true);
        
        //Buttons
        option1.setVisible(false);
        option2.setVisible(false);
        option3.setVisible(false);
        option4.setVisible(false);
        
        option5.setVisible(true);       
        option6.setVisible(true);    
        option7.setVisible(true);       
        option8.setVisible(true);
        
    }//GEN-LAST:event_option1ActionPerformed

    private void option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        
        //Current Question 
        CurrentQLbl1.setVisible(true);
        CurrentQLbl.setVisible(false);
        
        //Question Headings
        qLbl.setVisible(false);
        qLbl1.setVisible(true);
        
        //Questions
        QuestionLbl.setVisible(false);
        QuestionLbl1.setVisible(true);
        
        //Buttons
        option1.setVisible(false);       
        option2.setVisible(false);    
        option3.setVisible(false);       
        option4.setVisible(false);
        
        option5.setVisible(true);       
        option6.setVisible(true);    
        option7.setVisible(true);       
        option8.setVisible(true);
        
    }//GEN-LAST:event_option2ActionPerformed

    private void option4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        
         //Current Question 
        CurrentQLbl1.setVisible(true);
        CurrentQLbl.setVisible(false);
        
        //Question Headings
        qLbl.setVisible(false);
        qLbl1.setVisible(true);
        
        //Questions
        QuestionLbl.setVisible(false);
        QuestionLbl1.setVisible(true);
        
        //Buttons
        option1.setVisible(false);
        option2.setVisible(false);
        option3.setVisible(false);   
        option4.setVisible(false);
        
        option5.setVisible(true);       
        option6.setVisible(true);    
        option7.setVisible(true);       
        option8.setVisible(true);
     
    }//GEN-LAST:event_option4ActionPerformed

    private void option3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3ActionPerformed
        // TODO add your handling code here:
        wrongA++;
    
        //Current Question 
        CurrentQLbl1.setVisible(true);
        CurrentQLbl.setVisible(false);
        
        //Question Headings
        qLbl.setVisible(false);
        qLbl1.setVisible(true);
        
        //Questions
        QuestionLbl.setVisible(false);
        QuestionLbl1.setVisible(true);
        
        //Buttons 
        option1.setVisible(false);
        option2.setVisible(false);
        option3.setVisible(false);
        option4.setVisible(false);
        
        option5.setVisible(true);       
        option6.setVisible(true);    
        option7.setVisible(true);       
        option8.setVisible(true);
  
    }//GEN-LAST:event_option3ActionPerformed

    private void option6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option6ActionPerformed
        // TODO add your handling code here:
        correctA++;
        //Current Question 
        CurrentQLbl2.setVisible(true);
        CurrentQLbl1.setVisible(false);
        
        //Question Headings
        qLbl.setVisible(false);
        qLbl1.setVisible(false);
        qLbl2.setVisible(true);
        
        
        //Questions
        QuestionLbl1.setVisible(false);
        QuestionLbl2.setVisible(true);
        
        //Buttons
        option8.setVisible(false);
        option7.setVisible(false);
        option6.setVisible(false);
        option5.setVisible(false);
        
        option9.setVisible(true);       
        option10.setVisible(true);    
        option11.setVisible(true);       
        option12.setVisible(true);
     
        
        
    }//GEN-LAST:event_option6ActionPerformed

    private void option5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option5ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        //Current Question 
        CurrentQLbl2.setVisible(true);
        CurrentQLbl1.setVisible(false);
        
        //Question Headings
        qLbl.setVisible(false);
        qLbl1.setVisible(false);
        qLbl2.setVisible(true);
        
        //Questions
        QuestionLbl1.setVisible(false);
        QuestionLbl2.setVisible(true);
        
        //Buttons
        option8.setVisible(false);
        option7.setVisible(false);
        option6.setVisible(false);
        option5.setVisible(false);
        
        option9.setVisible(true);       
        option10.setVisible(true);    
        option11.setVisible(true);       
        option12.setVisible(true);
     
    }//GEN-LAST:event_option5ActionPerformed

    private void option7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option7ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        //Current Question 
        CurrentQLbl2.setVisible(true);
        CurrentQLbl1.setVisible(false);
        
        //Question Headings
        qLbl2.setVisible(true);
        qLbl1.setVisible(false);
        
        //Questions
        QuestionLbl1.setVisible(false);
        QuestionLbl2.setVisible(true);
        
        //Buttons
        option8.setVisible(false);
        option7.setVisible(false);
        option6.setVisible(false);
        option5.setVisible(false);
        
        option9.setVisible(true);       
        option10.setVisible(true);    
        option11.setVisible(true);       
        option12.setVisible(true);

    }//GEN-LAST:event_option7ActionPerformed

    private void option8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option8ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        //Current Question 
        CurrentQLbl2.setVisible(true);
        CurrentQLbl1.setVisible(false);
        
        //Question Headings
        qLbl2.setVisible(true);
        qLbl1.setVisible(false);
        
        //Questions
        QuestionLbl1.setVisible(false);
        QuestionLbl2.setVisible(true);
        
        //Buttons
        option8.setVisible(false);
        option7.setVisible(false);
        option6.setVisible(false);
        option5.setVisible(false);
        
        option9.setVisible(true);       
        option10.setVisible(true);    
        option11.setVisible(true);       
        option12.setVisible(true);

    }//GEN-LAST:event_option8ActionPerformed

    private void option9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option9ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        
        //Current Question
        CurrentQLbl2.setVisible(false);
        CurrentQLbl3.setVisible(true);
        
        //Question Headings#
        qLbl2.setVisible(false);
        qLbl3.setVisible(true);
     
        
        //Questions
        QuestionLbl2.setVisible(false);
        QuestionLbl3.setVisible(true);
        
        //Buttons
        option9.setVisible(false);
        option10.setVisible(false);
        option11.setVisible(false);
        option12.setVisible(false);
        
        option13.setVisible(true);       
        option14.setVisible(true);    
        option15.setVisible(true);       
        option16.setVisible(true);
 
    }//GEN-LAST:event_option9ActionPerformed

    private void option10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option10ActionPerformed
        // TODO add your handling code here:
        correctA++;
       
        //Current Question
        CurrentQLbl2.setVisible(false);
        CurrentQLbl3.setVisible(true);
        
        //Question Headings
        qLbl2.setVisible(false);
        qLbl3.setVisible(true);
       
        
        //Questions
        QuestionLbl2.setVisible(false);
        QuestionLbl3.setVisible(true);
        
        //Buttons
        option9.setVisible(false);
        option10.setVisible(false);
        option11.setVisible(false);
        option12.setVisible(false);
        
        option13.setVisible(true);       
        option14.setVisible(true);    
        option15.setVisible(true);       
        option16.setVisible(true); 
    }//GEN-LAST:event_option10ActionPerformed

    private void option11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option11ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        //Current Question
        CurrentQLbl2.setVisible(false);
        CurrentQLbl3.setVisible(true);
        
        //Question Headings
        qLbl2.setVisible(false);
        qLbl3.setVisible(true);
    
        
        //Questions
        QuestionLbl2.setVisible(false);
        QuestionLbl3.setVisible(true);
        
        //Buttons
        option9.setVisible(false);
        option10.setVisible(false);
        option11.setVisible(false);
        option12.setVisible(false);
        
        option13.setVisible(true);       
        option14.setVisible(true);    
        option15.setVisible(true);       
        option16.setVisible(true);
    }//GEN-LAST:event_option11ActionPerformed

    private void option12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option12ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        //Current Question
        CurrentQLbl2.setVisible(false);
        CurrentQLbl3.setVisible(true);
        
        //Question Headings
        qLbl2.setVisible(false);
        qLbl3.setVisible(true);
        
        
        //Questions
        QuestionLbl2.setVisible(false);
        QuestionLbl3.setVisible(true);
        
        //Buttons
        option9.setVisible(false);
        option10.setVisible(false);
        option11.setVisible(false);
        option12.setVisible(false);
        
        option13.setVisible(true);       
        option14.setVisible(true);    
        option15.setVisible(true);       
        option16.setVisible(true);
    }//GEN-LAST:event_option12ActionPerformed

    private void option13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option13ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        //Buttons   
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        CurrentQLbl3.setVisible(false);
    
        
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        
        }
        else{
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        
        option17.setVisible(true);       
        option18.setVisible(true);    
        option19.setVisible(true);       
        option20.setVisible(true);
 
       //Current Question
        CurrentQLbl3.setVisible(false);
        CurrentQLbl4.setVisible(true);
        
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        QuestionLbl4.setVisible(true);
        PicQ1.setVisible(true);
        }
    }//GEN-LAST:event_option13ActionPerformed

    private void option14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option14ActionPerformed
        // TODO add your handling code here:
        wrongA++; 
        //Buttons   
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        CurrentQLbl3.setVisible(false);
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        
        }
        else{
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        
        option17.setVisible(true);       
        option18.setVisible(true);    
        option19.setVisible(true);       
        option20.setVisible(true);
       //Current Question
        CurrentQLbl3.setVisible(false);
        CurrentQLbl4.setVisible(true);
        
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        QuestionLbl4.setVisible(true);
        PicQ1.setVisible(true);
        }
    }//GEN-LAST:event_option14ActionPerformed

    private void option15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option15ActionPerformed
        // TODO add your handling code here:
        correctA++;
        //Buttons   
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        CurrentQLbl3.setVisible(false);
    
        
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        
        }
        else{
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        
        option17.setVisible(true);       
        option18.setVisible(true);    
        option19.setVisible(true);       
        option20.setVisible(true);
       //Current Question
        CurrentQLbl3.setVisible(false);
        CurrentQLbl4.setVisible(true);
        
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        QuestionLbl4.setVisible(true);
        PicQ1.setVisible(true);
        }
    }//GEN-LAST:event_option15ActionPerformed

    private void option16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option16ActionPerformed
        // TODO add your handling code here:
        wrongA++;

        
        //Buttons   
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        CurrentQLbl3.setVisible(false);
    
        
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        
        }
        else{
        option13.setVisible(false);
        option14.setVisible(false);
        option15.setVisible(false);
        option16.setVisible(false);
        
        option17.setVisible(true);       
        option18.setVisible(true);    
        option19.setVisible(true);       
        option20.setVisible(true);
       //Current Question
        CurrentQLbl3.setVisible(false);
        CurrentQLbl4.setVisible(true);
        
        qLbl3.setVisible(false);

        //Questions
        QuestionLbl3.setVisible(false);
        QuestionLbl4.setVisible(true);
        PicQ1.setVisible(true);
        }
    }//GEN-LAST:event_option16ActionPerformed

    private void option17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option17ActionPerformed
        // TODO add your handling code here:
        correctA++;
        
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        RestartBtn.setVisible(true);
        
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(false);
        
 
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(false);
        PicQ1.setVisible(false);
        }
        
        else{              
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(true);
        
        //Questions
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(true);
        PicQ1.setVisible(false);

        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        
        option21.setVisible(true);       
        option22.setVisible(true);    
        option23.setVisible(true);       
        option24.setVisible(true);   
        }
    }//GEN-LAST:event_option17ActionPerformed

    private void option18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option18ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        //Current Question
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        RestartBtn.setVisible(true);
        
 
        
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(false);
        
 
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(false);
        PicQ1.setVisible(false);
      
        }
        
        else{              
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(true);
        
        //Questions
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(true);
        PicQ1.setVisible(false);

        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        
        option21.setVisible(true);       
        option22.setVisible(true);    
        option23.setVisible(true);       
        option24.setVisible(true);        

        }
    }//GEN-LAST:event_option18ActionPerformed

    private void option19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option19ActionPerformed
       // TODO add your handling code here:
        wrongA++;

       
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        RestartBtn.setVisible(true);
        
 
        
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(false);
        
 
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(false);
        PicQ1.setVisible(false);
        
        }
        
        else{              
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(true);
        
        //Questions
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(true);
        PicQ1.setVisible(false);

        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        
        option21.setVisible(true);       
        option22.setVisible(true);    
        option23.setVisible(true);       
        option24.setVisible(true);       
        }
    }//GEN-LAST:event_option19ActionPerformed

    private void option20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option20ActionPerformed
        // TODO add your handling code here:
        wrongA++;

       
        if(wrongA>=3){
        JOptionPane.showMessageDialog(null,"You are out of lives.");
        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        RestartBtn.setVisible(true);
        
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(false);
        
 
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(false);
        PicQ1.setVisible(false);
        
        }
        
        else{              
        CurrentQLbl4.setVisible(false);
        qLbl4.setVisible(true);
        
        option17.setVisible(false);
        option18.setVisible(false);
        option19.setVisible(false);
        option20.setVisible(false);
        
        option21.setVisible(true);   
        option22.setVisible(true);    
        option23.setVisible(true);       
        option24.setVisible(true); 

        //Questions
        QuestionLbl4.setVisible(false);
        QuestionLbl5.setVisible(true);
        PicQ1.setVisible(false);

        }
        
    }//GEN-LAST:event_option20ActionPerformed

    private void option21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option21ActionPerformed
        // TODO add your handling code here:
        wrongA++;

        
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false);
            RestartBtn.setVisible(true);
            
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
        else{
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false);  
            
            option25.setVisible(true);       
            option26.setVisible(true);    
            option27.setVisible(true);       
            option28.setVisible(true); 
            
            CurrentQLbl6.setVisible(true);
            QuestionLbl6.setVisible(true);
            PicQ2.setVisible(true);
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
        
    }//GEN-LAST:event_option21ActionPerformed

    private void option22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option22ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false);
            RestartBtn.setVisible(true);
            
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
        else{
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false); 
            
            option25.setVisible(true);       
            option26.setVisible(true);    
            option27.setVisible(true);       
            option28.setVisible(true);         

            CurrentQLbl6.setVisible(true);
            QuestionLbl6.setVisible(true);
            PicQ2.setVisible(true);
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
    }//GEN-LAST:event_option22ActionPerformed

    private void option23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option23ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false);
            RestartBtn.setVisible(true);
            
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
        else{
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false); 
            
            option25.setVisible(true);       
            option26.setVisible(true);    
            option27.setVisible(true);       
            option28.setVisible(true);         

            CurrentQLbl6.setVisible(true);
            QuestionLbl6.setVisible(true);
            PicQ2.setVisible(true);
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
        
    }//GEN-LAST:event_option23ActionPerformed

    private void option24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option24ActionPerformed
        // TODO add your handling code here:
        correctA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false);
            RestartBtn.setVisible(true);
            
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
        else{
            option21.setVisible(false);
            option22.setVisible(false);
            option23.setVisible(false);
            option24.setVisible(false);  
            
            option25.setVisible(true);       
            option26.setVisible(true);    
            option27.setVisible(true);       
            option28.setVisible(true);          

            CurrentQLbl6.setVisible(true);
            QuestionLbl6.setVisible(true);
            PicQ2.setVisible(true);
            qLbl4.setVisible(false);
            QuestionLbl5.setVisible(false);
        }
        
    }//GEN-LAST:event_option24ActionPerformed

//Breaks the array 
    private void RestartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartBtnActionPerformed
        // TODO add your handling code here:
        option1.setVisible(true);
        option2.setVisible(true);
        option3.setVisible(true);
        option4.setVisible(true);
        RestartBtn.setVisible(false);
        
        QuestionLbl.setVisible(true);
        qLbl.setVisible(true);
        CurrentQLbl.setVisible(true);
        
        correctA=0;
        wrongA=0;  
    }//GEN-LAST:event_RestartBtnActionPerformed

    private void option25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option25ActionPerformed
        // TODO add your handling code here:
        correctA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl6.setVisible(false);
            QuestionLbl6.setVisible(false);                      
        }
        
        else{
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false); 
            
            option29.setVisible(true);       
            option30.setVisible(true);    
            option31.setVisible(true);       
            option32.setVisible(true); 
            
            CurrentQLbl6.setVisible(false);
            CurrentQLbl7.setVisible(true);
            QuestionLbl6.setVisible(false);
            QuestionLbl7.setVisible(true);
            PicQ2.setVisible(false);
            qLbl5.setVisible(false);
            qLbl6.setVisible(true);
        }       
    }//GEN-LAST:event_option25ActionPerformed

    private void option26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option26ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl6.setVisible(false);
            QuestionLbl6.setVisible(false);                      
        }
        
        else{
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false); 
            
            option29.setVisible(true);       
            option30.setVisible(true);    
            option31.setVisible(true);       
            option32.setVisible(true);            
    
            CurrentQLbl6.setVisible(false);
            CurrentQLbl7.setVisible(true);
            QuestionLbl6.setVisible(false);
            QuestionLbl7.setVisible(true);
            PicQ2.setVisible(false);
            qLbl5.setVisible(false);
            qLbl6.setVisible(true);
        }       
    }//GEN-LAST:event_option26ActionPerformed

    private void option27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option27ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl6.setVisible(false);
            QuestionLbl6.setVisible(false);                      
        }
        
        else{
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false); 
            
            option29.setVisible(true);       
            option30.setVisible(true);    
            option31.setVisible(true);       
            option32.setVisible(true);           

            CurrentQLbl6.setVisible(false);
            CurrentQLbl7.setVisible(true);
            QuestionLbl6.setVisible(false);
            QuestionLbl7.setVisible(true);
            PicQ2.setVisible(false);
            qLbl5.setVisible(false);
            qLbl6.setVisible(true);
        }       
    }//GEN-LAST:event_option27ActionPerformed

    private void option28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option28ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl6.setVisible(false);
            QuestionLbl6.setVisible(false);                      
        }
        
        else{
            option25.setVisible(false);
            option26.setVisible(false);
            option27.setVisible(false);
            option28.setVisible(false); 
            
            option29.setVisible(true);       
            option30.setVisible(true);    
            option31.setVisible(true);       
            option32.setVisible(true); 
            
            CurrentQLbl6.setVisible(false);
            CurrentQLbl7.setVisible(true);
            QuestionLbl6.setVisible(false);
            QuestionLbl7.setVisible(true);
            PicQ2.setVisible(false);
            qLbl5.setVisible(false);
            qLbl6.setVisible(true);
        }       
    }//GEN-LAST:event_option28ActionPerformed

    private void option29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option29ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl7.setVisible(false);
            QuestionLbl7.setVisible(false);
            qLbl6.setVisible(false);
        }
        
        else{
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false); 
           
            option33.setVisible(true);       
            option34.setVisible(true);    
            option35.setVisible(true);       
            option36.setVisible(true);
            
            CurrentQLbl7.setVisible(false);
            CurrentQLbl8.setVisible(true);
            QuestionLbl7.setVisible(false);
            QuestionLbl8.setVisible(true);
            qLbl6.setVisible(false);
            qLbl7.setVisible(true);
        
        }
    }//GEN-LAST:event_option29ActionPerformed

    private void option30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option30ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl7.setVisible(false);
            QuestionLbl7.setVisible(false);
            qLbl6.setVisible(false);
        }
        
        else{
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false);
            
            option33.setVisible(true);       
            option34.setVisible(true);    
            option35.setVisible(true);       
            option36.setVisible(true);            

            CurrentQLbl7.setVisible(false);
            CurrentQLbl8.setVisible(true);
            QuestionLbl7.setVisible(false);
            QuestionLbl8.setVisible(true);
            qLbl6.setVisible(false);
            qLbl7.setVisible(true);
        
        }
        
    }//GEN-LAST:event_option30ActionPerformed

    private void option31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option31ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl7.setVisible(false);
            QuestionLbl7.setVisible(false);
            qLbl6.setVisible(false);
        }
        
        else{
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false);

            option33.setVisible(true);       
            option34.setVisible(true);    
            option35.setVisible(true);       
            option36.setVisible(true);
            
            CurrentQLbl7.setVisible(false);
            CurrentQLbl8.setVisible(true);
            QuestionLbl7.setVisible(false);
            QuestionLbl8.setVisible(true);
            qLbl6.setVisible(false);
            qLbl7.setVisible(true);
        }
    }//GEN-LAST:event_option31ActionPerformed

    private void option32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option32ActionPerformed
        // TODO add your handling code here:
        correctA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl7.setVisible(false);
            QuestionLbl7.setVisible(false);
            qLbl6.setVisible(false);
        }
        
        else{
            option29.setVisible(false);
            option30.setVisible(false);
            option31.setVisible(false);
            option32.setVisible(false);
            
            option33.setVisible(true);       
            option34.setVisible(true);    
            option35.setVisible(true);       
            option36.setVisible(true); 

            CurrentQLbl7.setVisible(false);
            CurrentQLbl8.setVisible(true);
            QuestionLbl7.setVisible(false);
            QuestionLbl8.setVisible(true);
            qLbl6.setVisible(false);
            qLbl7.setVisible(true);
        }
    }//GEN-LAST:event_option32ActionPerformed

    private void option33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option33ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl8.setVisible(false);
            QuestionLbl8.setVisible(false);
            qLbl7.setVisible(false);
        }
        
        else{
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false); 
            
            option37.setVisible(true);       
            option38.setVisible(true);    
            option39.setVisible(true);       
            option40.setVisible(true);  
            
            CurrentQLbl9.setVisible(true);
            CurrentQLbl8.setVisible(false);
            QuestionLbl9.setVisible(true);
            QuestionLbl8.setVisible(false);
            qLbl7.setVisible(false);
            qLbl8.setVisible(true);
        }
    }//GEN-LAST:event_option33ActionPerformed

    private void option34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option34ActionPerformed
        // TODO add your handling code here:
        correctA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl8.setVisible(false);
            QuestionLbl8.setVisible(false);
            qLbl7.setVisible(false);
        }
        
        else{
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false); 
            
            option37.setVisible(true);       
            option38.setVisible(true);    
            option39.setVisible(true);       
            option40.setVisible(true); 
            
            CurrentQLbl9.setVisible(true);
            CurrentQLbl8.setVisible(false);
            QuestionLbl9.setVisible(true);
            QuestionLbl8.setVisible(false);
            qLbl8.setVisible(true);
            qLbl7.setVisible(false);
        }
    }//GEN-LAST:event_option34ActionPerformed

    private void option35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option35ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl8.setVisible(false);
            QuestionLbl8.setVisible(false);
            qLbl7.setVisible(false);
        }
        
        else{
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false); 
            
            option37.setVisible(true);       
            option38.setVisible(true);    
            option39.setVisible(true);       
            option40.setVisible(true);
            
            CurrentQLbl9.setVisible(true);
            CurrentQLbl8.setVisible(false);
            QuestionLbl9.setVisible(true);
            QuestionLbl8.setVisible(false);
            qLbl8.setVisible(true);
            qLbl7.setVisible(false);
        }
    }//GEN-LAST:event_option35ActionPerformed

    private void option36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option36ActionPerformed
        // TODO add your handling code here:
        wrongA++;
        if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl8.setVisible(false);
            QuestionLbl8.setVisible(false);
            qLbl7.setVisible(false);
        }
        
        else{
            option33.setVisible(false);
            option34.setVisible(false);
            option35.setVisible(false);
            option36.setVisible(false); 
            
            option37.setVisible(true);
            option38.setVisible(true);
            option39.setVisible(true);
            option40.setVisible(true);
           
            
            CurrentQLbl9.setVisible(true);
            CurrentQLbl8.setVisible(false);
            QuestionLbl9.setVisible(true);
            QuestionLbl8.setVisible(false);
            qLbl8.setVisible(true);
            qLbl7.setVisible(false);
        }
    }//GEN-LAST:event_option36ActionPerformed

    private void option37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option37ActionPerformed
        // TODO add your handling code here:
        wrongA++;
            if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
        
        else{
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false); 

            Score1.setVisible(true);
            NameLbl.setVisible(true);
            EnterBtn.setVisible(true);
            NameTF.setVisible(true);
            conGrts.setVisible(true);
            SaveBtn.setVisible(true);
            
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
    }//GEN-LAST:event_option37ActionPerformed

    private void option38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option38ActionPerformed
        // TODO add your handling code here:
        wrongA++;
            if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
        
        else{
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false); 
            
            Score1.setVisible(true);
            NameLbl.setVisible(true);
            EnterBtn.setVisible(true);
            NameTF.setVisible(true);  
            conGrts.setVisible(true);
            SaveBtn.setVisible(true);
            
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
    }//GEN-LAST:event_option38ActionPerformed

    private void option39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option39ActionPerformed
        // TODO add your handling code here:
        correctA++;
            if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false);
            RestartBtn.setVisible(true);
            
            
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
        
        else{
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false); 
            
            Score1.setVisible(true);
            NameLbl.setVisible(true);
            EnterBtn.setVisible(true);
            NameTF.setVisible(true);   
            conGrts.setVisible(true);
            SaveBtn.setVisible(true);
            
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
    }//GEN-LAST:event_option39ActionPerformed

    private void option40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option40ActionPerformed
        // TODO add your handling code here:
         wrongA++;
            if(wrongA>=3){
            JOptionPane.showMessageDialog(null,"You are out of lives.");
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false);
            RestartBtn.setVisible(true);
           
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
        
        else{
            option37.setVisible(false);
            option38.setVisible(false);
            option39.setVisible(false);
            option40.setVisible(false); 
           
            NameLbl.setVisible(true);
            EnterBtn.setVisible(true);
            NameTF.setVisible(true);  
            conGrts.setVisible(true);
            SaveBtn.setVisible(true);
            
            CurrentQLbl9.setVisible(false);
            QuestionLbl9.setVisible(false);
            qLbl8.setVisible(false);
        }
    }//GEN-LAST:event_option40ActionPerformed

    private void EnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBtnActionPerformed
        // TODO add your handling code here:
        name = NameTF.getText();
      
        Score1.setVisible(true);
        Score1.setText(name+", "+correctA);
        
        Trivia t = new Trivia();
        t.setName(name);
        t.setCorrectA(correctA);
        ql.add(t);
        JOptionPane.showMessageDialog(null,"Name and score added");
        
        EnterBtn.setVisible(false);
        RestartBtn.setVisible(true);
        SaveBtn.setVisible(false);
        NameTF.setVisible(false);  
        NameLbl.setVisible(false);
        conGrts.setVisible(false);
        
        count++;
    }//GEN-LAST:event_EnterBtnActionPerformed

    private void DisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtnActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < ql.size();i++){
            JOptionPane.showMessageDialog(null,"High scores \n"+ql.get(i).getName()+":"+correctA); 
        }
    }//GEN-LAST:event_DisplayBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Your score was saved.");
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriviaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriviaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriviaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriviaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriviaFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JLabel CurrentQLbl;
    private javax.swing.JLabel CurrentQLbl1;
    private javax.swing.JLabel CurrentQLbl2;
    private javax.swing.JLabel CurrentQLbl3;
    private javax.swing.JLabel CurrentQLbl4;
    private javax.swing.JLabel CurrentQLbl5;
    private javax.swing.JLabel CurrentQLbl6;
    private javax.swing.JLabel CurrentQLbl7;
    private javax.swing.JLabel CurrentQLbl8;
    private javax.swing.JLabel CurrentQLbl9;
    private javax.swing.JButton DisplayBtn;
    private javax.swing.JButton EnterBtn;
    private javax.swing.JToggleButton HomeBtn;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel PicQ1;
    private javax.swing.JLabel PicQ2;
    private javax.swing.JPanel QuestionArea;
    private javax.swing.JLabel QuestionLbl;
    private javax.swing.JLabel QuestionLbl1;
    private javax.swing.JLabel QuestionLbl2;
    private javax.swing.JLabel QuestionLbl3;
    private javax.swing.JLabel QuestionLbl4;
    private javax.swing.JLabel QuestionLbl5;
    private javax.swing.JLabel QuestionLbl6;
    private javax.swing.JLabel QuestionLbl7;
    private javax.swing.JLabel QuestionLbl8;
    private javax.swing.JLabel QuestionLbl9;
    private javax.swing.JButton RestartBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel Score1;
    private javax.swing.JLabel Score2;
    private javax.swing.JPanel ScoreArea;
    private javax.swing.JLabel Title;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel conGrts;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton option1;
    private javax.swing.JButton option10;
    private javax.swing.JButton option11;
    private javax.swing.JButton option12;
    private javax.swing.JButton option13;
    private javax.swing.JButton option14;
    private javax.swing.JButton option15;
    private javax.swing.JButton option16;
    private javax.swing.JButton option17;
    private javax.swing.JButton option18;
    private javax.swing.JButton option19;
    private javax.swing.JButton option2;
    private javax.swing.JButton option20;
    private javax.swing.JButton option21;
    private javax.swing.JButton option22;
    private javax.swing.JButton option23;
    private javax.swing.JButton option24;
    private javax.swing.JButton option25;
    private javax.swing.JButton option26;
    private javax.swing.JButton option27;
    private javax.swing.JButton option28;
    private javax.swing.JButton option29;
    private javax.swing.JButton option3;
    private javax.swing.JButton option30;
    private javax.swing.JButton option31;
    private javax.swing.JButton option32;
    private javax.swing.JButton option33;
    private javax.swing.JButton option34;
    private javax.swing.JButton option35;
    private javax.swing.JButton option36;
    private javax.swing.JButton option37;
    private javax.swing.JButton option38;
    private javax.swing.JButton option39;
    private javax.swing.JButton option4;
    private javax.swing.JButton option40;
    private javax.swing.JButton option5;
    private javax.swing.JButton option6;
    private javax.swing.JButton option7;
    private javax.swing.JButton option8;
    private javax.swing.JButton option9;
    private javax.swing.JLabel qLbl;
    private javax.swing.JLabel qLbl1;
    private javax.swing.JLabel qLbl2;
    private javax.swing.JLabel qLbl3;
    private javax.swing.JLabel qLbl4;
    private javax.swing.JLabel qLbl5;
    private javax.swing.JLabel qLbl6;
    private javax.swing.JLabel qLbl7;
    private javax.swing.JLabel qLbl8;
    // End of variables declaration//GEN-END:variables
}